# Generated by Django 5.1.5 on 2025-01-28 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_end_date_event_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='contactEmail',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='contactPhone',
            new_name='contact_phone',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='zipCode',
            new_name='zip_code',
        ),
    ]
