# Generated by Django 5.1.5 on 2025-01-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_end_time_alter_event_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tickets_left',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
